### ISSUE TITLE
Buttons are not working

### ISSUE THREAD

**Issue by mpagels** [mayinx/edmeda#3]
When I click this button, nothing happens:
![Bildschirmfoto 2021-08-17 um 15 23 27](https://user-images.githubusercontent.com/54703643/129733635-6333c3d0-3741-426e-9ffa-8421397ceed4.png)

And this button as well:
![Bildschirmfoto 2021-08-17 um 15 24 39](https://user-images.githubusercontent.com/54703643/129733710-00c25339-ab34-4ccd-93ad-b9f14094b700.png)

**Comment by mayinx** [comment]
Of course not ...
