### ISSUE TITLE
When I click "Create your first community" an empty page is shown...

### ISSUE THREAD

**Issue by mpagels** [mayinx/edmeda#4]
...and nothing more. I expected to see some sort of input, where I can create a community.

**Comment by mayinx** [comment]
Thanks - Will investigate this - I think I didn't update link that opens the modal...

**Comment by mayinx** [comment]
Yep - that was it - when working with test data that button doesn't show up that often, that's why that bug slipped through  - had still a `<Link to="newCommunity" ...>` instead of an  `<Link to="communities/new" ...>`  - fixed now  with PR #2 ...
