### ISSUE TITLE
[Client] [MyCommunities] Info message is telling me, to choose a unique community name, but I can add the same community without problems

### ISSUE THREAD

**Issue by mpagels** [mayinx/edmeda#6]
![Bildschirmfoto 2021-08-17 um 15 44 01](https://user-images.githubusercontent.com/54703643/129736771-30a1b529-2df6-4840-be38-1a3060780a29.png)

**Comment by mayinx** [comment]
True, of course - I need to wire up the client-side-validation with a server request for available / already taken community names etc. - but that's (with regard to the very limited available time) a topic for a later iteration, when the basic app works etc. - so I leave that issue open

**Comment by mpagels** [comment]
THX for letting me know.

**Comment by mayinx** [comment]
Closed with PR #14
