### ISSUE TITLE
When opening a community an empty screen is showing

### ISSUE THREAD

**Issue by mpagels** [mayinx/edmeda#7]
![Bildschirmfoto 2021-08-17 um 16 19 48](https://user-images.githubusercontent.com/54703643/129743203-54a6069d-53a6-469b-b115-4143e67c08fb.png)

And no button to get back to the main screen with the communities.

**Comment by mayinx** [comment]
That hurts my feelings, bro ;-) - "*nothing is shown*" ?  It's the 1st draft of the base structure for the current community page - like in: "work in progress" ...

**Comment by mpagels** [comment]
;-) Never push "work in progress" to production or to the user ;-)
